export const COURSES = [
  "Estratégia Concursos – Direito Constitucional (2025) – Profa. Nelma Fontana",
  "Grancursos – Inglês para Concursos (2025) – Prof. Roberto Witte",
  "Habilitação de Oficiais da Polícia Militar de Minas Gerais (2025) – Ag_Concurso",
  "Formação de Sargentos da Polícia Militar de Minas Gerais (2025) – Ag_Concurso",
  "Português — Kuadro",
  "Física — Kuadro",
  "Matemática — Kuadro",
  "História — Kuadro",
  "Química — Kuadro",
  "Exame CFC Essencial 2024",
  "Curso de Direito Tributário – Pós-Reforma (2024) – Prof. Fabio Dutra",
  "Curso Completo de Direito Penal (2025) – Profa. Priscila Silveira",
  "Curso de Fisiologia e Anatomia Humana Completo para Concursos (2025) – Prof. André Dávila",
  "Direito Civil para as Carreiras Jurídicas (2024) – Prof. Daniel Carnacchioni",
  "OAB – Preparação para 1ª Fase do 40º Exame de Ordem + Curso Extensivo Completo (2025)",
  "Curso Completo de Atualidades para Concursos (2024) – Prof. Leandro Signori",
  "O Plano ENEM (2025) – Gilberto Augusto",
  "INSS (Técnico do Seguro Social) Pacotaço – Pacote Teórico + Pacote Passo (2024–2025)",
  "Agência Nacional de Aviação Civil (ANAC)",
  "Passando em Tudo – Eu Militar",
  "EBSERH (Grupo 4 – Enfermagem) – Enfermeiro",
  "Preparação para Polícias Civis de São Paulo e Distrito Federal – Delegado (Pré-Edital) – Gran Cursos Online",
  "Chama o Físico – Aulas Extensivo",
  "PC MG – Delegado de Polícia Civil de Minas Gerais",
  "Português Extensivo – Professor Andresan",
  "UFRJ – Universidade Federal do Rio de Janeiro – Conhecimentos Comuns a Todos os Cargos",
  "Instituto Brasileiro de Geografia e Estatística (IBGE)",
  "História Geral — Curso Completo para Concursos — Rodrigo Donin",
  "Aprovação 2.0 – Gilberto Augusto",
  "Português Vip Cespe Cebraspe – Grasiela Cabral",
  "STN – Secretaria do Tesouro Nacional — Conhecimentos Gerais (Comum a Todas as Áreas) (Pós-Edital)",
  "Caixa Econômica Federal (CEF) — Técnico Bancário (Pacote Completo + Cursos Bônus)",
  "Curso Essencial Concursos para Guardas Municipais",
  "Direito Administrativo do Zero — Papa Concursos (2023)",
  "Papa Concursos Direito Civil — Ridison Lucas (2023)",
  "Curso Completo de Contabilidade Avançada — Prof. Marcondes",
  "Isoladas — Papa Concursos",
  "Curso Completo de Contabilidade Pública — Prof. Marcondes",
  "Lições de Física 2023 — Universo Narrado",
  "Linguagens — Fernanda Pessoa",
  "Cursos de Exatas — Descomplica",
  "Engenharia de Produção — Transpetro e Petro — Estratégia Concursos",
  "Perito 4.0 — IAPA",
  "Combo PF + PRF — Estratégia Concursos 2023",
  "Português — Estratégia Vestibulares 2023",
  "Direito Constitucional — Estratégia Concursos (2022)",
  "INSS Técnico do Seguro Social — Estratégia Concursos (2022)",
  "Direito Processual Penal — Estratégia Concursos (2022)",
  "Raciocínio Lógico — Estratégia Concursos (2022)",
  "Português: A Gramática para Concursos Públicos — Fernando Pestana",
  "Noções de Informática — Estratégia Concursos (2022)",
  "ENAM – Exame Nacional da Magistratura (1º Exame) (Pós-Edital) – Curso Intensivo",
  "CFC Curso de Física (2024) – Fininho",
  "Pacote Completo para Iniciantes (Nível Médio) (2024) – Estratégia Concursos",
  "Secretarias de Educação – SEED e SMEs: Pacote Completo para Professor de Educação Física",
  "Pacote Completo para Iniciantes (Nível Superior) – Estratégia Concursos",
  "SME–João Pessoa (Professor II – Matemática) Pacote (2024) – Estratégia Concursos",
  "SEEDUC-RJ (Professor – História) Pacote (2024) – Estratégia Concursos",
  "BNDES – Profissional Básico: Análise de Sistemas – Desenvolvimento",
  "TJ-SP (Escrevente Técnico Judiciário) Pacotaço – Pacote Teórico + Pacote Passo Estratégico (2024)",
  "Dominando o Cálculo (2024) – Tem Ciência",
  "Revisão AFA/EsPCEx (2024) – Felipe Guisoli e Engenheiro",
  "EEAR (2024) – Estratégia Militares",
  "Receita Federal (Auditor Fiscal) Pacotaço – Pacote Teórico + Pacote Passo Estratégico (2024)",
  "Tribunal Superior Eleitoral – TSE (Unificado e Servidores)",
  "EEAR – Triunfo Militar (2023)",
  "Pacote – PRF (Policial Rodoviário Federal) Pacotaço",
  "Técnico Administrativo – ANAC",
  "Concursos Federais – Pacote Principais Disciplinas",
  "CAF – Curso de Matemática Básica – Guilherme Centragnolo (2024)",
  "UFPB (Assistente em Administração) Pacote – 2024 (Pós-Edital)",
  "Correios (Agente de Correios – Carteiro) Pacotaço – 2024 (Pós-Edital)",
  "BACEN (Analista – Área 2 – Economia e Finanças) Pacotaço",
  "Curso Exclusivo de Direito Constitucional – Adriane Fauth (2020)",
  "PMERJ – Eu Militar Concursos (2022)",
  "Toda a Matemática Cálculo 1 (2024) – Gustavo Viegas",
  "PM-ES (Oficial Combatente) Pacotaço – 2024 (Pós-Edital)",
  "STJ (2024) (Analista Judiciário – Psicologia) Pacote – (Pós-Edital)",
  "Projeto Elétrico CPE – Marcelo Oliveira (2024)",
  "OAB 1ª Fase 40º Exame – CEISC (2024)",
  "TRT-SE 20ª Região (Técnico Judiciário – Área Administrativa) Pacotaço – 2024 (Pós-Edital)",
  "Contabilidade Geral e Avançada – Estratégia Concursos (2024)",
  "Extensivo – Residência Médica – Estratégia – MED (2024)",
  "CEMIG Informática Básica Pós Edital – Renato da Costa (2023)",
  "Matemática e Raciocínio Lógico Banca FGV – José Neto (2022)",
  "Universo Narrado Lições de Matemática – Felipe Guisoli (2023)",
  "Português Descomplicado para Concursos – Yara Coeli (2019)",
  "Contabilidade para Polícia Federal – Gabriel Rabelo",
  "SEE-PB (Professor – Física) Pacote Pré-Edital (2023)",
  "Polícia Federal Perito Criminal Informática – GranCursos (2023)",
  "Banco do Brasil – Escriturário – Agente Comercial – Estratégia (2023)",
  "Polícia Rodoviária Federal (PRF) – Gran Cursos (2022)",
  "O Curso dos Modelos e Ponto-Luma e Ponto (2023)",
  "Curso Online Física – Douglas Gomes",
  "ABIN Cargo 1 – Oficial de Inteligência Área 4 – GranCursos (2022)",
  "TJ RN – Técnico Judiciário e Oficial de Justiça – GranCursos (2023)",
  "Matemática para Concursos – Márcio Flávio (2022)",
  "Agente da Polícia Federal – Estratégia Concursos (2023)",
  "Português: A Gramática para Concursos – Arnaldo Martino (2013)",
  "Treinamento para Concursos Militares – Mautama Coach Militar (2022)",
  "Pacote para Concursos (Área de TI) – Cursos Regulares",
  "Direito Processual do Trabalho – Papa Concursos (2023)",
  "Polícia Federal (Agente de Polícia) Estatística – Pré-Edital (2023)",
  "Praticando Matemática – Maicon Meneguci (2023)",
  "Português – Estratégia Concursos (2022)",
  "Analista Receita Federal Brasileira – Estratégia Concursos",
  "Adriana Figueiredo (2023) – Pack",
  "Português GOLD – Flávia Rita (2023)",
  "Secretarias de Educação – SEED e SMEs (Cursos Regulares) Pacote Completo para Professor de Matemática – 2023",
  "Disciplinas Complementares Federais e Estaduais – G7 Jurídico (2022)",
  "Contabilidade Pública para Concursos – Estratégia Concursos (2023)",
  "Polícia Científica PR (Perito Oficial) Pacote de Conhecimentos Básicos (Pré-Edital) – 2023",
  "Técnico Judiciário – Administrativa – Estratégia Concursos (2023)",
  "Auditor Fiscal do Trabalho – Estratégia Concursos (2023)",
  "Inglês para Concursos Militares – Sérgio Gama (2020)",
  "Estratégia Concursos – Curso Exclusivo de Português – Adriana Figueiredo",
  "Estatística para Concursos – Jhoni Zini",
  "Alberto Dell’isola – Auto-Hipnose para Provas e Concursos",
  "Curso de Formação de Sargentos – Infoway Concursos",
  "Passo-a-passo do Cronograma Militar Perfeito (2023)",
  "MED APROVA BASIC – Focus Vestibulares (2023)",
  "Física para ENEM – Prof. Henrique Goulart (2023)",
  "Biblioteconomia p/ Concursos – Curso Regular (2023)",
  "Polícia Militar do Rio de Janeiro (PM-RJ) – Oficial (2023)",
  "Curso Completo de Atualidades para Concursos – Prof. Leandro Signori (2023)",
  "Caixa Econômica Federal Técnico Bancário PCD – Nova Concursos (2022)",
  "Banco do Brasil Escriturário Tecnologia – Estratégia Concursos (2023)",
  "PM-CE (Soldado) Pacotaço – Pacote Teórico + Pacote Passo Estratégico",
  "TSE – Concurso Unificado – Técnico Judiciário – Agente da Polícia Judicial",
  "SEFAZ-RJ – Auditor Fiscal – Pacotaço",
  "TSE – Concurso Unificado – Técnico Judiciário – Área Administrativa",
  "BNB (Analista Bancário) Pacotaço – 2023 (Pré-Edital)",
  "TCU (Auditor de Controle – Área Controle Externo) Pacotaço – 2023 (Pré-Edital)"
];
